### ISSUE TITLE
SCSS usage

### ISSUE THREAD

**Issue by longnd** [ltenzil/scrape#20]
The application is implementing SCSS, why not using its syntax to nest the classes?
https://github.com/ltenzil/scrape/blob/6eb163261a9102f748fc789147840f7856584ef8/app/assets/stylesheets/sidebar.scss#L31-L38

There is also another sidebar class on top
https://github.com/ltenzil/scrape/blob/6eb163261a9102f748fc789147840f7856584ef8/app/assets/stylesheets/sidebar.scss#L31-L38

can be changed to
```scss
.sidebar {
  .nav-link {
  ...
  }
  
  ....
}
...

**Comment by ltenzil** [comment]
Yeah, I did that in signin.scss file, I forgot to do it sidebar.scss. 
I am a beginner in css styling, I learnt how to use frameworks. (foundation, semantic-ui, learning bootstrap )
https://github.com/ltenzil/scrape/blob/6eb163261a9102f748fc789147840f7856584ef8/app/assets/stylesheets/signin.scss#L1-L11

**Comment by ltenzil** [comment]
Resolved in #21

**Comment by longnd** [comment]
While there are still some improvements that can be done but that PR did fix the issue and enough for us to evaluate. This issue is closed now. Thank you for the fix.
